### ISSUE TITLE
[StorageNodeRegistry] Create contract.

### ISSUE THREAD

**Issue by ITStar10** [verida/blockchain-contracts#118]
Create a contract : https://github.com/verida/VIPs/pull/4

**Comment by tahpot** [comment]
Let's expand the scope of this issue.

1. Expand `StorageNodeInput` to support `numberSlots` (integer) indicating how many storage slots the node will provide.
2. The number of tokens required to stake must be defined in a variable (`STAKE_PER_SLOT`). Only contract owner can change this variable. Initial value is 60 VDA tokens.
3. When `addNode()` is called, the requester must provide VDA tokens to stake. The number of staked tokens must be `numberSlots` * `STAKE_PER_SLOT`. The staked tokens should be registered against the storage node being registered.
4. When `removeNode()` is called, the staked tokens for that storage node should be released to the requester of this call.
5. Add a new method `withdraw()` allowing the requester to remove tokens for a given storage node. They must provide a signed request proving they control the private key of the storage node. If the `STAKE_PER_SLOT` goes down, then the storage node owner can withdraw excess tokens.
6. Add a new method `deposit()` allowing a storage node owner to add more tokens to a given storage node. They must provide a signed request proving they control the private key of the storage node. If the `STAKE_PER_SLOT` goes up, then the storage node owner can deposit additional tokens.

Note: We have not yet handled the scenario where `STAKE_PER_SLOT` is increased and storage node operators do not have enough tokens staked. This will be handled later. We will implement storage node operators earning a revenue from their nodes. They won't be able to earn revenue if they don't have enough tokens staked.

**Comment by ITStar10** [comment]
> 6. Add a new method `deposit()` ...

**Here, I think, we don't need to provide the signed request. We can deposit the token amount from any requestor to that didAddress as following:**
```
function depoistToken(address didAddress, uint tokenAmount) external;
```

**And this `deposit()` function will work for only the registered DIDs, correct?**

**Comment by tahpot** [comment]
> > 6. Add a new method `deposit()` ...
> >    Here, I think, we don't need the provide the signed request. We can deposit the token amount from any requestor to that didAddress as following:
> 
> ```
> function depoistToken(address didAddress, uint tokenAmount) external;
> ```
> 
> **And this `deposit()` function will work for only the registered DIDs, correct?**

Yes, correct.
