### ISSUE TITLE
[vda-reward-contract] Support claiming to storage

### ISSUE THREAD

**Issue by tahpot** [verida/blockchain-contracts#136]
We want the ability for a user to claim rewards, but instead of having the rewards allocated to their wallet address, the rewards are added to their storage credits.

As such, we need a new method:

```
function claim(
        string calldata typeId, 
        string calldata hash, 
        bytes calldata signature,
        bytes calldata proof
    )
```

Note: There is no `address to` property, instead the tokens will be transferred to the `VDA-Storage-Node` contract and owned by the `DID` associated with this claim request.

**Comment by ITStar10** [comment]
Pls consider following:
1. The reward token of the `VDA-Reward-Contract` should be always our Verida token contract. Also this token contract address should be the same as the `tokenAddress` of the `VDA-StorageNode-Registry` contract.
2. To directly transfer the tokens to the `VDA-StorageNode-Registry` contract, we should keep the address of `VDA-StorageNode-Registry` contract inside the `VDA-Reward-Contract`. It involves the update of the infrastructure and init functions of the `VDA-Reward-Contract`. Can we redeploy the `VDA-Reward-Contract` in the testnet and mainnet?
3. To implement the main feature of this issue#136, we should call the `depositToken()` of the `VDA-StorageNode-Registry` contract. Not explaining all the details, but this'd be a bit complex stuffs. Pls consider following 2 ways:
-- Add function for this feature to the `VDA-StorageNode-Registry` contract.
-- Add a package for the `VDA-Reward-Contract` in the `verida-js` and implement this feature without any contract updates.

**Comment by tahpot** [comment]
1. Yes, correct.
2. Yes, we can redeploy, they aren't being used
3. Add a function to `VDA-StorageNode-Registry` should be okay.
