### ISSUE TITLE
[storage-credits] Support locking tokens

### ISSUE THREAD

**Issue by tahpot** [verida/blockchain-contracts#156]
**Add a new method `lock(did: string, purpose: string, amount: uint)`. This locks the specified number of tokens for a specific purpose for a specific did.**

For example, a did may lock 1,000 VDA tokens for the purpose of early-access-verida-ai

**Requirements:**

- The lock() request must by signed by the did. Throws invalid request signature
- The method may accept VDA tokens sent in the requests, otherwise it will allocate tokens previously deposit()ed into the did’s credit.
- The method may return insufficient funds error if there are not enough tokens included in the request or there are not enough token credits in the smart contract for the requesting did.
- A `did` can call lock multiple times to add more tokens.

**Add a new method `locked(did: string, purpose: string)`. This returns the number of tokens locked by a did for a specific purpose.**

**Requirements:**

If there are no tokens locked for the specified did and purpose, throws did has no locked tokens for this purpose.

**Add a new method `unlock(did: string, purpose: string, withdrawWallet: string | undefined)`. This unlocks all the tokens locked for the specified purpose.**

**Requirements:**

- The unlock() request must be signed by the did. Throws invalid request signature
- The method may return lock does not exist error.
- If withdrawWallet is specified, the amount of tokens should be withdrawn to the specified wallet, otherwise the tokens will be deposited as credit for the did.

**Comment by ITStar10** [comment]
@tahpot Designed the `lock()` function as following:
```ts
  function lock(
    address didAddress,
    string calldata purpose,
    uint amount,
    bool withDeposit,
    bytes calldata requestSignature,
    bytes calldata requestProof
  ) external;

```

**Comment by ITStar10** [comment]
>  locked(did: string, purpose: string) 

How about to return 0 for unknown `purpose`s instead of throwing error?

**Comment by ITStar10** [comment]
** unlock() **
I designed the function as following:
```ts
  function unlock(
    address didAddress,
    string calldata purpose,
    address to,
    bytes calldata requestSignature,
    bytes calldata requestProof
  ) external;
```

The `to` address can't be optional. If we don't specified the recipient wallet address, the transaction can be attacked by the front-running attackers.
In your design, the `withrdawAddress` is optional, in case, we should unlock to the `msg.sender` correct?
The attackers monitors the mempool and clone a user's `unlock` transaction and send it with more gases. The contract will unlock the tokens to the attacker.

**Comment by ITStar10** [comment]
Also, I think we need a function get the list of registered `purpose` for a given DID.
```ts
function getPurposeList(address didAddress, uint pageSize, uint pageNumber) returns (string[] memory)
```

**Comment by tahpot** [comment]
> > locked(did: string, purpose: string)
> 
> How about to return 0 for unknown `purpose`s instead of throwing error?

That’s fine

**Comment by tahpot** [comment]
> > locked(did: string, purpose: string)
> 
> How about to return 0 for unknown `purpose`s instead of throwing error?

That’s fine

**Comment by tahpot** [comment]
> ** unlock() ** I designed the function as following:
> 
> ```ts
>   function unlock(
>     address didAddress,
>     string calldata purpose,
>     address to,
>     bytes calldata requestSignature,
>     bytes calldata requestProof
>   ) external;
> ```
> 
> The `to` address can't be optional. If we don't specified the recipient wallet address, the transaction can be attacked by the front-running attackers. In your design, the `withrdawAddress` is optional, in case, we should unlock to the `msg.sender` correct? The attackers monitors the mempool and clone a user's `unlock` transaction and send it with more gases. The contract will unlock the tokens to the attacker.

Aren’t we protected from this because the request signature includes the address?

**Comment by tahpot** [comment]
> Also, I think we need a function get the list of registered `purpose` for a given DID.
> 
> ```ts
> function getPurposeList(address didAddress, uint pageSize, uint pageNumber) returns (string[] memory)
> ```

Agree

**Comment by ITStar10** [comment]
> unlock()
If we don't specify the recipient address, the transaction'd be as following:
```ts
unlock(didAddress, purpose, requestSignature, requestProof)
```
If there is no recipient address, we'd unlock the token to the transaction caller.
By the way, the attacker hook this transaction information from the mempool before the transaction completed.
The attacker will submit the same transaction with higher gas.
The contract only verify the didAddress and purpose with requestSignature and requestProof. There is no logic that checks the transaction caller.
So, the transaction of the attacker is completed first and the original transaction will be reverted.

**Comment by ITStar10** [comment]
So, we should include the recipient address in the parameter.
```ts
unlock(didAddress, purpose, recipient, requestSignature, requestProof)
```
In case, though any attackers clone this transaction, the tokens will be unlocked to the recipient address.

**Comment by tahpot** [comment]
> > unlock()
> > If we don't specify the recipient address, the transaction'd be as following:
> 
> ```ts
> unlock(didAddress, purpose, requestSignature, requestProof)
> ```
> 
> If there is no recipient address, we'd unlock the token to the transaction caller. By the way, the attacker hook this transaction information from the mempool before the transaction completed. The attacker will submit the same transaction with higher gas. The contract only verify the didAddress and purpose with requestSignature and requestProof. There is no logic that checks the transaction caller. So, the transaction of the attacker is completed first and the original transaction will be reverted.

The tokens should never be released to the blockchain wallet caller. If. i wallet address is specified, the tokens are added as credit to the DID.
