### ISSUE TITLE
Create Minimal Soulbound Token smart contract (EIP-5484)

### ISSUE THREAD

**Issue by tahpot** [verida/blockchain-contracts#57]
We want to start issuing Soulbound Tokens to users.

Implement a basic smart contract based on [EIP-5192: Minimal Soulbound NFTs](https://eips.ethereum.org/EIPS/eip-5192).

It must extend `ERC721Metadata` as per [EIP 721](https://eips.ethereum.org/EIPS/eip-721).

Call the smart contract `Soulbound-NFT` and deploy to MATIC Mumbai testnet for testing.

This issue is for a basic MVP. The more detailed requirements will come later.

**Comment by ITStar10** [comment]
## NFT Mint persmission
There might 2 options to mint NFTs to users:
- Only owenr mint NFTs to the users.
- Users can mint by paying native token(MATIC in Polygon) or our Verida token
- Users can mint NFT freely

**Which option should we use?**
## Questions regarding Solbound-NFT.
- What will be the mint price? Anyone can mint freely?
- Do we mint NFT to Verida account or general Wallet account?
I think, we should mint NFT to Verdia account. In case, we need signature verification step on minting.
If we mint NFTs to Verida account, we should override many functions of original ERC721 contract. We should add signature verification to functions.
- Is there any limits to NFT counts? A user can owe only one NFT or more?

## IERC5192
- When will the `Unlocked(uint256 tokenId)` event raise? There is no function to unlock the locked token in ERC721. Should I add a function named `unlock(uint256 tokenId)`?
- What will the result of `locked(uint256 tokenId)` function of IERC5192?
There is a `burn` feature in the NFT. Once token burnt, the owner would be dead address.

**Comment by tahpot** [comment]
Great questions @ITStar10.

## NFT mint permission

Users can mint their own NFTs, **however** they will need to provide a proof to mint the NFT. We will need to add the verification base contract capabilities to this NFT contract. I need to write up a scoping document for this.

Basically; A user will provide a proof of something off-chain that allows them to mint a NFT. For example:

- A proof they own a twitter account, signed by a trusted Verida DID
- A proof they have 10k twitter followers, signed by a trusted Verida DID

## Questions regarding Soulbound NFTs

>1. What will be the mint price? Anyone can mint freely?

No mint price, anyone can mint.

>2. Do we mint NFT to Verida account or general Wallet account?

NFT's will be minted to the user's Wallet account.

>3. I think, we should mint NFT to Verdia account. In case, we need signature verification step on minting.

Why do you think we should mint NFT to Verida account?

>4. If we mint NFTs to Verida account, we should override many functions of original ERC721 contract. We should add signature verification to functions.

> 5. Is there any limits to NFT counts? A user can own only one NFT or more?

There are no limits.

**Comment by tahpot** [comment]
## Example flow

1. User signs into their Twitter account and authorizes a Verida server to gain an access token
2. Verida server generates a proof string (`twitter-${twitterId}-${did}`) and signs it using a Verida Company DID that represents a "trusted signer" on the Verida network
3. Verida server sends the signed proof to the User, who stores it in their Vault
4. The user clicks a `claim` button in the Vault to claim a SBT
5. The user sends the signed proof to the SBT smart contract, with a wallet address, along with a signature that combines the contract params and a nonce (using the Verida Verification Base process)
6. The NFT uses the Verida Verification Base smart contract library to verify the signature, verify the signed proof matches the Verida Company DID and then mints an NFT for the user's crypto wallet
7. A user receives a NFT in their requested wallet address
8. A SBT can only be claimed once per wallet, per `SBT type`

## SBT types

1. `twitter-account`
2. `facebook-account`
3. `linkedin-account`

## Requirements

1. Support adding / removing Verida company DIDs (owner only)
2. Support adding / removing (owner only)
3. Support a `claimSbt()` function
