### ISSUE TITLE
[vda-erc20] Audit feedback

### ISSUE THREAD

**Issue by tahpot** [verida/blockchain-contracts#80]
Action required:

1. `enableMaxAmountPerWallet` -- Set to `onlyOwner`
2. `enableMaxAmountPerSell` -- Set to `onlyOwner`
3. `VDA-Lock.sol` and `RecipientLockUp.sol` -- `require(userInfo.lockType == 0, "Can not add an existing lock holder")`
at the beginning of the function and to remove the if statement on line 123
4.  `VDA-V1.sol: Internal function to initialise the uniswap features is not called anywhere.` -- This will be updated with values for polygon. `_initSwap` will be called from the initializer function or at least anywhere else in the contract if this function needs to be used, otherwise, remove unused code.
5. `VDA-Lock.sol: Claim function does not truly require nonReentrant modifier.` -- Will remove
6. `VDA-Lock.sol: addLockHolder does not follow the correct check, effect, interact order` -- Move token.mint call after the userInfo changes
7. `Verida Protocol: Pragma Solidity Version` -- Will be updated to latest before publishing to mainnet
8. `VDA-Lock.sol, RecipientLockUp.sol: Gas wasted on claim function.` -- Will be updated to use `require()`

**Comment by ITStar10** [comment]
3 : Current logic is following:
Only the contract owner can call this `addLockHolder()` function. If the owner add a lockholder with wrong info - such as wrong lockAmount - the owner can update by call this function again with correct info.
line#124 is checking that.
If we use `require(userInfo.lockType == 0)`, the contract owner can not update the lockHolder information. To do so, contract owner should call `removeLockHolder()` function and then `addLockHolder()` function.

**Comment by tahpot** [comment]
Closing this issue as our plans have changed.
