### ISSUE TITLE
[VDA-SBT] IsClaimedSBT() and GetClaimedSBTList() update

### ISSUE THREAD

**Issue by ITStar10** [verida/blockchain-contracts#95]
- Can't check whether SBT is claimed with SBTType & UniqueID. Only the owner of SBT can check this
- Update to check anybody can check whit SBTType & UniqueID

Now, `isSBTClaimed(...)` function in the smart contract checks whether the sbt is claimed to the function caller (`msg.sender`). This is inconvenient in following cases:
- In the `verida-js/vda-sbt-client`, we create the vda-sbt-client with DID. This instance can call `isSBTClaimed()` function to check the claimed information regarding the DID. If there are multiple wallets for this DID, this instance can't check multiple wallets.
- In the Polygon scan (https://mumbai.polygonscan.com/ for test net), we can't call this `isSBTClaimed()` function manually, because we can't connect wallt for Read functions:
![image](https://user-images.githubusercontent.com/15656252/224594723-91d66312-f0f9-498c-a1bb-071aeb091d95.png)

Same for `getClaimedSBTList()` function.

**Comment by tahpot** [comment]
This change allows calling `isSBTClaimed()` and `GetClaimedSBTList()` by anyone, not just owner.
