### ISSUE TITLE
[Verification contracts] Check & update test code of contracts for verida-js update

### ISSUE THREAD

**Issue by ITStar10** [verida/blockchain-contracts#97]
- Check test codes that uses the keyring to make signedData & signedProof
- Need to test contract that inherits the VerificationBase contract

**Comment by tahpot** [comment]
`verida-js` had some changes that relate to introducing `@verida/types` package.

This has broken some of the `blockchain-contract` unit tests.

This issue is to fix those unit tests using the updated protocol.
